name: my-first-github-action-cicd
on: [push]
jobs:
  build_node:
    runs-on: ubuntu-latest
    container: node:25
    steps:
      - run: echo "Hello, World!"
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node app.js
